name: Testing VERA GPU Micro-Apps

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bradenpecora/vera-gpu:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build and test
        run: |
          . /opt/spack-environment/activate.sh
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel 4
          cd build
          ctest -j4 --output-on-failure -E "heavy_test"
