name: Testing VERA GPU Micro-Apps

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bradenpecora/vera-gpu:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Configure project
        shell: bash
        run: |
          echo "Original LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          # Add CUDA compat path
          export LD_LIBRARY_PATH="/usr/local/cuda-12.4/compat:${LD_LIBRARY_PATH}"
          echo "LD_LIBRARY_PATH after adding CUDA compat: $LD_LIBRARY_PATH"
          source /opt/spack-environment/activate.sh # Spack will prepend its paths
          echo "LD_LIBRARY_PATH after Spack activate: $LD_LIBRARY_PATH"
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=mpicxx

      - name: Build project
        shell: bash
        run: |
          # Add CUDA compat path
          export LD_LIBRARY_PATH="/usr/local/cuda-12.4/compat:${LD_LIBRARY_PATH}"
          source /opt/spack-environment/activate.sh
          cmake --build build --parallel 4

      - name: Run tests
        shell: bash
        run: |
          echo "--- Debugging Information (Pre-Test) ---"
          echo "Original LD_LIBRARY_PATH for test step: $LD_LIBRARY_PATH"
          # Add CUDA compat path
          export LD_LIBRARY_PATH="/usr/local/cuda-12.4/compat:${LD_LIBRARY_PATH}"
          echo "LD_LIBRARY_PATH after adding CUDA compat for test step: $LD_LIBRARY_PATH"
          source /opt/spack-environment/activate.sh # Spack will prepend its paths
          echo "LD_LIBRARY_PATH after Spack activate for test step: $LD_LIBRARY_PATH"
          echo ""
          echo "Current directory: $(pwd)"
          echo "Searching for libcuda.so.1 in Spack directories:"
          find /opt/views -name libcuda.so.1 -ls
          find /opt/software -name libcuda.so.1 -ls
          echo ""
          echo "Checking /usr/local/cuda-12.4/compat/ (from base image):"
          ls -l /usr/local/cuda-12.4/compat/libcuda.so.1
          echo ""
          echo "ldd output for a failing test executable:"
          # Adjust path if necessary
          ldd /__w/vera_gpu_micro_app/vera_gpu_micro_app/build/cmfd/CMFD-test_PETSc_ex3k.kokkos
          echo "--- End Debugging Information (Pre-Test) ---"
          cd build
          ctest -j4 --output-on-failure -E "heavy_test"
