name: Testing VERA GPU Micro-Apps

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: micahbest/vera-gpu:latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure project
        run: |
          cmake -B build

      - name: Build project
        run: |
          cmake --build build --parallel 4

      - name: Run tests
        run: |
          cd build
          ctest -j4 --output-on-failure
