name: Testing VERA GPU Micro-Apps

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bradenpecora/vera-gpu:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Configure project
        run: |
          export PATH=/opt/views/view/bin:$PATH
          which mpicxx
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=mpicxx

      - name: Build project
        run: |
          export PATH=/opt/views/view/bin:$PATH
          cmake --build build --parallel 4

      - name: Run tests
        run: |
          export PATH=/opt/views/view/bin:$PATH
          cd build
          ctest -j4 --output-on-failure -E "heavy_test"
