name: Testing VERA GPU Micro-Apps

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: micahbest/vera-gpu:latest

    env:
      CMAKE_BUILD_TYPE: Release

    steps:
      - uses: actions/checkout@v4

      - name: Configure project
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
            -DCMAKE_PREFIX_PATH="/opt/kokkos;/opt/highfive \
            -DKokkos_DIR=/opt/kokkos/lib/cmake/Kokkos \
            -DPETSc_DIR=/opt/petsc-arch/lib/cmake/PETSc

      - name: Build project
        run: |
          cmake --build build --parallel 4

      - name: Run tests
        run: |
          cd build
          ctest -j4 --output-on-failure
